# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 18:18
from __future__ import unicode_literals

import audiofield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(default=b'', max_length=100)),
                ('artist_image', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='ListenCount',
            fields=[
                ('listen_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(default=b'', max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayListSong',
            fields=[
                ('playlist_song_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PlayList')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(default=b'', max_length=100)),
                ('song_file', audiofield.fields.AudioField(blank=True, upload_to=b'')),
                ('song_image', models.FileField(blank=True, upload_to=b'')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Song'),
        ),
        migrations.AddField(
            model_name='listencount',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Song'),
        ),
        migrations.AddField(
            model_name='listencount',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Artist'),
        ),
    ]
