# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_auto_20180710_1738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listencount',
            unique_together=set([('user_id', 'song_id')]),
        ),
    ]
