# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180710_1822'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set([('album_id', 'artist_id')]),
        ),
    ]
